CREATE DATABASE iF NOT EXISTS assign2;
USE assign2;
CREATE TABLE reg1(
regId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cname VARCHAR(50) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
mob BIGINT UNIQUE NOT NULL
);

select *
FROM  reg1;